### PR TITLE
fix typo in README, change wsm_client_create() API

### PR DESCRIPTION
**Pull request by Tarnyko**
Hello,

Please look at "https://github.com/Tarnyko/weston-wayland_security_module" for an initial implementation with this change :-)

### CODE REVIEW

**Comment by Tarnyko** [comment]
Bump ?

**Comment by Sidnioulz** [comment]
Hi Tarnyko,

Don't worry, we didn't forget you!

@mupuf  is currently in holidays, but should be able to reply shortly! If not then I'll look at the commit myself and enforce a decision without him in ~1 week.

Cheers,

**Comment by mupuf** [comment]
Sorry Tarnyko, I actually started reviewing your patches when I came back home but I had to try hard to recall what was my plan, 3 months ago.

Anyway, let's start the review!

Patch 1: Reviewed-by: Martin Peres <martin.peres@free.fr>

Patch2, I think your patch is doing 3 things at the same time:

 - The CMakeLists.txt changes are in my opinion un-necessary as libwsm already has a hard dependency on libwayland-server. Looking at the code again, I do not however see why I linked with it since I never used it. The commit message is ... empty... That's what happens when you only have a few days to beat an idea into shape... Anyway, I have had this internal debate for quite some time about whether libwsm should depend on libwayland-server or not and I seemed to have decided not since libwsm does not have to know about the internals of the IPC system that is defined in libwayland.
I am thus now considering dropping this dependency for the moment. More info on this in a second comment.

  - Dropping the fd field may have some serious implications. How about adding another version of wsm_client_create that takes a wsn_client instead of an fd? However, I am not convinced about the need. The only reason why you need this is because you use wsm_client_create at the wrong time. You are supposed to have it called at client initialization (when the client connects to the server) and delete it when the client gets disconnected. This is needed because the backend may do some tracking of the client's operations if it chooses to implement a non-static decision making. I would thus suggest reworking the second weston patch to first introduce the creation/deletion of the wsm_client and then a second patch that checks for the fullscreen.

- Modifying the test: I suggest reviewing the logic here for the different fds since the original one was fine. The only thing you would really have needed is to init the wayland display and then client. In any case, I am not convinced that we need to change this test because of what I said in the previous paragraph.

**Comment by mupuf** [comment]
I have been thinking about the idea of having libwsm directly in libwayland-server. This would allow compositors not to have a ton of #ifdef in case the lib is not present. Also, the default implementation in libwayland-server could just return SOFT_ALLOW by default if not backend is present.

Another good point about having libwsm integrated in libwayland-server is that it becomes possible to also intercept all the low-level messages which would allow some sort of RPC-level access control that would not require any changes at all to the compositors. This is of course not always sufficient but that is quite interesting to have such a thing if gnome really is going to hardcode all their policy :s

**Comment by mupuf** [comment]
Other than that, thanks for looking into this! My productivity outside of work is close has been close to 0 but I am slowly improving it as I really settle in :)

**Comment by Tarnyko** [comment]
Hi @sidnioulz, @mupuf,

Thanks for the review ! Here are my notes on the 3 points and the additional comment ,:

* "CMakeLists.txt changes"
From what I recall, wayland-server was checked at configure time but nothing happened if it wasn't found (the variables weren't used later).

* "How about adding another version of wsm_client_create that takes a wsn_client instead of an fd?"
I am definitely buying this idea !

"You are supposed to have it called at client initialization (when the client connects to the server)"
Are you talking about doing this in the compositor, or in wayland-server directly ? If it is in the compositor, I definitely have to check again, didn't find the good spot but had very few time, too.

"I would thus suggest reworking the second weston patch to first introduce the creation/deletion of the wsm_client and then a second patch that checks for the fullscreen.".
Yes I get this ; having a "wsm_client_t" object created whenever a client connects, destroyed when it disconnects, and used once or more meanwhile. Will do this !

"I have been thinking about the idea of having libwsm directly in libwayland-server [...]  it becomes possible to also intercept all the low-level messages which would allow some sort of RPC-level access control that would not require any changes at all to the compositors."
You are totally right ; that would allow most of the requests (especially the "deny" ones) to be blocked or modifed before they even get to the compositor, thus enforcing the lib purpose without requiring duplicate work from various implementors.

On the other hand, and from a pragmatic (and RFC-ish) POV it might be better to first demonstrate lib usage in a compositor, thus demonstrating relevance and functionality before we eventually try to get something in wayland-server.
----
Considering this, here is what I will be trying to do :
- in the compositor, finding the good spot to use the current "wsm_client_create()" function ;
- if I am unable to do so, propose a new "wsm_wl_client_create()" function, whose presence or functionality would eventually depend on the presence of wayland-server at configure time ;
- rework the 2nd Weston patch to become less demo-ish and more generic  ("wsm_client_t" object following client lifetime).
- do a PR for all this first to you, and then upstream.

Thanks for your time, will be back !

**Comment by mupuf** [comment]
"From what I recall, wayland-server was checked at configure time but nothing happened if it wasn't found (the variables weren't used later)." --> LIBWSM is set to OFF if libwayland-server is not there.

"Yes I get this ; having a "wsm_client_t" object created whenever a client connects, destroyed when it disconnects, and used once or more meanwhile. Will do this !" --> You got it!

"On the other hand, and from a pragmatic (and RFC-ish) POV it might be better to first demonstrate lib usage in a compositor, thus demonstrating relevance and functionality before we eventually try to get something in wayland-server." --> I completely agree here! Let's first aim for adoption before asking to be merged :)

Your plan seems good, although I am not sure I understand what you mean by PR.

Have fun!

**Pull request closed without merging**
